version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: ferahahmed/node_app
    ports:
      - "3002:3002"
    environment:
      - PG_DB=person
      - PG_USER=postgres
      - PG_PASSWORD=1234578
      - PG_HOST=localhost
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=person
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}